"""updated schema

Revision ID: a96bab9eb6b4
Revises: 3d0e2f2ed1f2
Create Date: 2026-07-15 12:51:53.418309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a96bab9eb6b4'
down_revision: Union[str, None] = '3d0e2f2ed1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old users table first since we're changing id from integer to UUID
    op.drop_table('users')
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('qdrant_point_id', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('guide', 'pattern', 'best_practice', 'security_hardening', 'cost_optimization')", name='ck_rag_documents_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_point_id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_url')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("agent_name IN ('codesec', 'infracost', 'deployops')", name='ck_agent_tasks_agent_name'),
    sa.CheckConstraint("status IN ('pending', 'started', 'success', 'failure', 'retrying')", name='ck_agent_tasks_status'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index(op.f('ix_agent_tasks_run_id'), 'agent_tasks', ['run_id'], unique=False)
    op.create_table('codesec_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remediation_hint', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scanner IN ('semgrep', 'gitleaks', 'trivy', 'bandit')", name='ck_codesec_findings_scanner'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_codesec_findings_severity'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_codesec_findings_run_id', 'codesec_findings', ['run_id'], unique=False)
    op.create_index('idx_codesec_findings_severity', 'codesec_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_codesec_findings_run_id'), 'codesec_findings', ['run_id'], unique=False)
    op.create_table('cost_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_usd', sa.Float(), nullable=False),
    sa.Column('actual_cost_usd', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("alert_type IN ('budget_exceeded', 'cost_spike', 'unusual_resource')", name='ck_cost_alerts_alert_type'),
    sa.CheckConstraint("severity IN ('warning', 'critical')", name='ck_cost_alerts_severity'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_alerts_project_id', 'cost_alerts', ['project_id'], unique=False)
    op.create_index('idx_cost_alerts_run_id', 'cost_alerts', ['run_id'], unique=False)
    op.create_index(op.f('ix_cost_alerts_project_id'), 'cost_alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_alerts_run_id'), 'cost_alerts', ['run_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('aws_region', sa.String(), nullable=False),
    sa.Column('terraform_version', sa.String(), nullable=True),
    sa.Column('terraform_state_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('infrastructure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_total_monthly', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('dev', 'staging', 'prod')", name='ck_deployments_environment'),
    sa.CheckConstraint("status IN ('pending', 'applying', 'succeeded', 'failed', 'rolled_back')", name='ck_deployments_status'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployments_run_id', 'deployments', ['run_id'], unique=False)
    op.create_index(op.f('ix_deployments_run_id'), 'deployments', ['run_id'], unique=False)
    op.create_table('infracost_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('monthly_cost_usd', sa.Float(), nullable=False),
    sa.Column('annual_cost_usd', sa.Float(), nullable=False),
    sa.Column('usage_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confidence_level IN ('high', 'medium', 'low')", name='ck_infracost_estimates_confidence'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_infracost_estimates_run_id', 'infracost_estimates', ['run_id'], unique=False)
    op.create_index(op.f('ix_infracost_estimates_run_id'), 'infracost_estimates', ['run_id'], unique=False)
    op.create_table('terraform_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("artifact_type IN ('terraform', 'dockerfile', 'docker-compose', 'cloudformation', 'helm', 'kubernetes', 'ansible', 'pulumi', 'bicep')", name='ck_terraform_artifacts_artifact_type'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_terraform_artifacts_run_id', 'terraform_artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_terraform_artifacts_run_id'), 'terraform_artifacts', ['run_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_finding_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_notifications_severity'),
    sa.CheckConstraint("type IN ('finding', 'deployment', 'cost_alert', 'security_breach')", name='ck_notifications_type'),
    sa.ForeignKeyConstraint(['related_finding_id'], ['codesec_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_run_id', 'notifications', ['run_id'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_run_id'), 'notifications', ['run_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_run_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_run_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_terraform_artifacts_run_id'), table_name='terraform_artifacts')
    op.drop_index('idx_terraform_artifacts_run_id', table_name='terraform_artifacts')
    op.drop_table('terraform_artifacts')
    op.drop_index(op.f('ix_infracost_estimates_run_id'), table_name='infracost_estimates')
    op.drop_index('idx_infracost_estimates_run_id', table_name='infracost_estimates')
    op.drop_table('infracost_estimates')
    op.drop_index(op.f('ix_deployments_run_id'), table_name='deployments')
    op.drop_index('idx_deployments_run_id', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_cost_alerts_run_id'), table_name='cost_alerts')
    op.drop_index(op.f('ix_cost_alerts_project_id'), table_name='cost_alerts')
    op.drop_index('idx_cost_alerts_run_id', table_name='cost_alerts')
    op.drop_index('idx_cost_alerts_project_id', table_name='cost_alerts')
    op.drop_table('cost_alerts')
    op.drop_index(op.f('ix_codesec_findings_run_id'), table_name='codesec_findings')
    op.drop_index('idx_codesec_findings_severity', table_name='codesec_findings')
    op.drop_index('idx_codesec_findings_run_id', table_name='codesec_findings')
    op.drop_table('codesec_findings')
    op.drop_index(op.f('ix_agent_tasks_run_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###