"""
DevGuard AI - Orchestrator State Definitions
==============================================
All TypedDict definitions for the orchestrator's LangGraph state, plus the
factory function that builds a fresh initial state for a new workflow.

Split out of graph.py (originally Section 1, 1.1, and create_initial_state
from Section 8) so that state shape can be reviewed/changed independently
from graph wiring, node logic, and human-gate logic.

Owner: Hbib (Subgroup 2 - Execution & Control)

NOTE: codesec_result is kept as a flexible dict (not a strict TypedDict) to
accept Nada's exact CodeSecResult payload without transformation (Option 1
strategy - "accept everything from Nada").
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Literal, Optional, TypedDict

# Single source of truth for the orchestrator version. graph.py imports this
# rather than repeating the string, so the value reported in state metadata
# and the value logged at compile time can never drift apart again (they did:
# state said 1.0.5 while the graph said 1.0.7).
GRAPH_VERSION = "1.3.1"

# Max feedback-driven regeneration rounds at Gate 2 before the user is forced
# to approve/reject. Guards against runaway LLM loops (and cost).
MAX_INFRACOST_ITERATIONS = 3


# =============================================================================
# SECTION 1: STATE DEFINITIONS
# =============================================================================

class InfraCostResult(TypedDict):
    """Output from InfraCost Agent (Karim)."""
    architecture_recommendation: Literal["ecs_fargate", "lambda", "ec2", "hybrid"]
    justification: str
    generated_terraform: dict
    cost_estimate: dict
    load_scenarios: list[dict]
    optimizations: list[dict]
    region_comparison: list[dict]


# =============================================================================
# SECTION 1.1: DEPLOYOPS TYPED DICTS (ALIGNED WITH deployops-mock-schema.json)
# =============================================================================

class HealthCheckResult(TypedDict):
    """
    Health check result - aligned with deployops-mock-schema.json.
    Required fields: passed, response_time_ms, status_code
    """
    passed: bool
    response_time_ms: int
    status_code: int
    checked_at: Optional[str]  # ISO 8601 date-time format


class DeployOpsArtifactsTerraform(TypedDict):
    """Terraform artifacts sub-structure."""
    files: dict[str, str]
    variables: dict[str, str]


class DeployOpsArtifacts(TypedDict):
    """Artifacts generated by deployment."""
    terraform: DeployOpsArtifactsTerraform
    dockerfile: str
    docker_image: dict[str, str]
    source_code: Optional[str]


class DeployOpsAwsConfig(TypedDict):
    """AWS configuration for deployment."""
    region: str
    ecs_cluster: str
    service_name: str
    task_cpu: str
    task_memory: str


class DeployOpsDeploymentConfig(TypedDict):
    """Deployment configuration."""
    strategy: Literal["rolling", "blue-green"]
    health_check_path: str
    health_check_port: int
    timeout_minutes: int
    min_healthy_percent: int
    max_percent: int


class DeployOpsApproval(TypedDict):
    """Approval information."""
    deploy_approved: bool
    approved_by: str  # email format


class TerraformOutputs(TypedDict):
    """Required Terraform outputs - aligned with deployops-mock-schema.json."""
    ecs_cluster_name: str
    service_name: str
    alb_dns: str


class DeployOpsResult(TypedDict):
    """
    Output from DeployOps Agent (Oussema).
    ALIGNED with deployops-mock-schema.json v1.0

    Required fields (schema): job_id, deployment_status, deployed_url,
    health_check, rollback_triggered, terraform_outputs
    """
    # ===== CHAMPS REQUIS par le schema =====
    job_id: str
    deployment_status: Literal["success", "failed", "rolled_back"]
    deployed_url: Optional[str]
    health_check: HealthCheckResult
    rollback_triggered: bool
    rollback_reason: Optional[str]
    error: Optional[str]
    terraform_outputs: TerraformOutputs  # Required, not Optional

    # ===== CHAMPS OPTIONNELS du schema =====
    artifacts: Optional[DeployOpsArtifacts]
    aws_config: Optional[DeployOpsAwsConfig]
    deployment_config: Optional[DeployOpsDeploymentConfig]
    approval: Optional[DeployOpsApproval]


class HumanGate(TypedDict):
    """Single human approval gate state."""
    required: bool
    approved: Optional[bool]
    comment: Optional[str]
    approved_at: Optional[str]
    approved_by: Optional[str]
    requested_changes: Optional[str]  # user feedback prompt for regeneration


class HumanGates(TypedDict):
    """All human approval gates."""
    gate_1_pre_infracost: HumanGate
    gate_2_pre_deployops: HumanGate


class InfracostIteration(TypedDict):
    """One feedback-driven regeneration round of the InfraCost agent."""
    iteration: int
    prompt: str
    result: dict
    requested_at: str


class ErrorEntry(TypedDict):
    """Single error entry in the error log."""
    node: str
    attempt: int
    max_attempts: int
    message: str
    timestamp: str
    stack_trace: Optional[str]
    resolved: bool


class OrchestratorMetadata(TypedDict):
    """Internal metadata for tracing and debugging."""
    graph_version: str
    start_time: str
    elapsed_seconds: float
    current_node: str
    nodes_executed: list[str]
    chat_session_id: Optional[str]


class FinalReportSummary(TypedDict):
    """Summary section of final report."""
    total_vulnerabilities: int
    critical_count: int
    estimated_monthly_cost_usd: float
    deployment_status: str
    recommendations: list[str]
    pipeline_duration_seconds: float


class FinalReport(TypedDict):
    """Final generated report."""
    format: Literal["pdf", "html", "json"]
    generated_at: str
    download_url: Optional[str]
    summary: FinalReportSummary


class OrchestratorState(TypedDict):
    """
    Main state object for the LangGraph workflow.
    ALIGNED with docs/api-contracts/orchestrator-input-schema.json

    IMPORTANT: codesec_result is a flexible dict (Option 1 strategy).
    It contains the EXACT payload from Nada's codesec-mock-schema.json.
    """
    job_id: str
    repo_url: str
    status: Literal[
        "pending", "cloning", "analyzing", "awaiting_approval_gate_1",
        "infra_generating", "awaiting_approval_gate_2", "deploying",
        "health_checking", "completed", "failed", "rolled_back",
        "rejected",
    ]
    created_at: str
    updated_at: str
    codesec_result: Optional[dict]  # <-- Flexible dict for Nada's exact payload
    infracost_result: Optional[InfraCostResult]
    deployops_result: Optional[DeployOpsResult]
    human_gates: HumanGates
    error_log: list[ErrorEntry]
    orchestrator_metadata: OrchestratorMetadata
    final_report: Optional[FinalReport]
    infracost_feedback: Optional[str]
    infracost_iterations: list[InfracostIteration]


# =============================================================================
# STATE FACTORY
# =============================================================================

def create_initial_state(repo_url: str, job_id: str | None = None) -> OrchestratorState:
    """Create the initial state for a new workflow."""
    now = datetime.now(timezone.utc).isoformat()
    job_id = job_id or str(uuid.uuid4())

    return {
        "job_id": job_id,
        "repo_url": repo_url,
        "status": "pending",
        "created_at": now,
        "updated_at": now,
        "codesec_result": None,
        "infracost_result": None,
        "deployops_result": None,
        "human_gates": {
            "gate_1_pre_infracost": {
                "required": True,
                "approved": None,
                "comment": None,
                "approved_at": None,
                "approved_by": None,
                "requested_changes": None,
            },
            "gate_2_pre_deployops": {
                "required": True,
                "approved": None,
                "comment": None,
                "approved_at": None,
                "approved_by": None,
                "requested_changes": None,
            },
        },
        "error_log": [],
        "orchestrator_metadata": {
            "graph_version": GRAPH_VERSION,
            "start_time": now,
            "elapsed_seconds": 0.0,
            "current_node": "start",
            "nodes_executed": [],
            "chat_session_id": None,
        },
        "final_report": None,
        "infracost_feedback": None,
        "infracost_iterations": [],
    }
