"""
DevGuard AI - Orchestrator Agent
LangGraph-based workflow orchestrator for the DevSecOps pipeline.

Owner: Hbib (Subgroup 2 - Execution & Control)
Branch: feature/hbib-orchestrator-skeleton

This module implements the core state graph that coordinates:
- CodeSec Agent (Nada) -> Security analysis
- InfraCost Agent (Karim) -> Infrastructure & cost estimation
- DeployOps Agent (Oussema) -> Deployment & health checks
- Human Approval Gates -> Human-in-the-loop validation
- Chat LLM -> Conversational interface with job context
- Error Handler -> Retry logic with exponential backoff

IMPORTANT: codesec_result uses the EXACT payload format from Nada's codesec-mock-schema.json
Option 1: "Accept everything from Nada" - no transformation, direct passthrough.

Sprint: 1 (Foundation & Mock Agents)
CDC Reference: Section 4.2 (Epic 2.2: Orchestrator Agent)

CHANGELOG:
- v1.0.1: Fixed error handling (removed time.sleep), secured dict access, added route guards
- v1.0.1: Added safe_node_wrapper for automatic error catching in graph nodes
- v1.0.1: Added pipeline timeout tracking
- v1.0.1: Fixed error_log resolved flag logic
- v1.0.1: Added conditional routing with failure checks
- v1.0.2: Aligned DeployOpsResult with deployops-mock-schema.json (Oussema)
- v1.0.2: Added job_id to DeployOpsResult (required by schema)
- v1.0.2: Changed terraform_outputs from Optional[dict] to dict (required by schema)
- v1.0.2: Added HealthCheckResult TypedDict for strict typing
- v1.0.2: Added job_id to mock_deployops_agent_impl payload
"""

from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Literal, Optional, TypedDict

# LangGraph imports
from langgraph.graph import StateGraph, END
from langgraph.types import interrupt
from langgraph.checkpoint.memory import MemorySaver

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# =============================================================================
# SECTION 1: STATE DEFINITIONS
# =============================================================================
# NOTE: codesec_result is kept as a flexible dict to accept Nada's exact payload.
# We do NOT define strict TypedDict for it (Option 1 strategy).

class InfraCostResult(TypedDict):
    """Output from InfraCost Agent (Karim)."""
    architecture_recommendation: Literal["ecs_fargate", "lambda", "ec2", "hybrid"]
    justification: str
    generated_terraform: dict
    cost_estimate: dict
    load_scenarios: list[dict]
    optimizations: list[dict]
    region_comparison: list[dict]


# =============================================================================
# SECTION 1.1: DEPLOYOPS TYPED DICTS (ALIGNED WITH deployops-mock-schema.json)
# =============================================================================

class HealthCheckResult(TypedDict):
    """
    Health check result - aligned with deployops-mock-schema.json.
    Required fields: passed, response_time_ms, status_code
    """
    passed: bool
    response_time_ms: int
    status_code: int
    checked_at: Optional[str]  # ISO 8601 date-time format


class DeployOpsArtifactsTerraform(TypedDict):
    """Terraform artifacts sub-structure."""
    files: dict[str, str]
    variables: dict[str, str]


class DeployOpsArtifacts(TypedDict):
    """Artifacts generated by deployment."""
    terraform: DeployOpsArtifactsTerraform
    dockerfile: str
    docker_image: dict[str, str]
    source_code: Optional[str]


class DeployOpsAwsConfig(TypedDict):
    """AWS configuration for deployment."""
    region: str
    ecs_cluster: str
    service_name: str
    task_cpu: str
    task_memory: str


class DeployOpsDeploymentConfig(TypedDict):
    """Deployment configuration."""
    strategy: Literal["rolling", "blue-green"]
    health_check_path: str
    health_check_port: int
    timeout_minutes: int
    min_healthy_percent: int
    max_percent: int


class DeployOpsApproval(TypedDict):
    """Approval information."""
    deploy_approved: bool
    approved_by: str  # email format


class TerraformOutputs(TypedDict):
    """Required Terraform outputs - aligned with deployops-mock-schema.json."""
    ecs_cluster_name: str
    service_name: str
    alb_dns: str


class DeployOpsResult(TypedDict):
    """
    Output from DeployOps Agent (Oussema).
    ALIGNED with deployops-mock-schema.json v1.0
    
    Required fields (schema): job_id, deployment_status, deployed_url, 
    health_check, rollback_triggered, terraform_outputs
    """
    # ===== CHAMPS REQUIS par le schema =====
    job_id: str
    deployment_status: Literal["success", "failed", "rolled_back"]
    deployed_url: Optional[str]
    health_check: HealthCheckResult
    rollback_triggered: bool
    rollback_reason: Optional[str]
    error: Optional[str]
    terraform_outputs: TerraformOutputs  # Required, not Optional
    
    # ===== CHAMPS OPTIONNELS du schema =====
    artifacts: Optional[DeployOpsArtifacts]
    aws_config: Optional[DeployOpsAwsConfig]
    deployment_config: Optional[DeployOpsDeploymentConfig]
    approval: Optional[DeployOpsApproval]


class HumanGate(TypedDict):
    """Single human approval gate state."""
    required: bool
    approved: Optional[bool]
    comment: Optional[str]
    approved_at: Optional[str]
    approved_by: Optional[str]


class HumanGates(TypedDict):
    """All human approval gates."""
    gate_1_pre_infracost: HumanGate
    gate_2_pre_deployops: HumanGate


class ErrorEntry(TypedDict):
    """Single error entry in the error log."""
    node: str
    attempt: int
    max_attempts: int
    message: str
    timestamp: str
    stack_trace: Optional[str]
    resolved: bool


class OrchestratorMetadata(TypedDict):
    """Internal metadata for tracing and debugging."""
    graph_version: str
    start_time: str
    elapsed_seconds: float
    current_node: str
    nodes_executed: list[str]
    chat_session_id: Optional[str]


class FinalReportSummary(TypedDict):
    """Summary section of final report."""
    total_vulnerabilities: int
    critical_count: int
    estimated_monthly_cost_usd: float
    deployment_status: str
    recommendations: list[str]
    pipeline_duration_seconds: float


class FinalReport(TypedDict):
    """Final generated report."""
    format: Literal["pdf", "html", "json"]
    generated_at: str
    download_url: Optional[str]
    summary: FinalReportSummary


class OrchestratorState(TypedDict):
    """
    Main state object for the LangGraph workflow.
    ALIGNED with docs/api-contracts/orchestrator-input-schema.json

    IMPORTANT: codesec_result is a flexible dict (Option 1 strategy).
    It contains the EXACT payload from Nada's codesec-mock-schema.json.
    """
    job_id: str
    repo_url: str
    status: Literal[
        "pending", "cloning", "analyzing", "awaiting_approval_gate_1",
        "infra_generating", "awaiting_approval_gate_2", "deploying",
        "health_checking", "completed", "failed", "rolled_back",
    ]
    created_at: str
    updated_at: str
    codesec_result: Optional[dict]  # <-- Flexible dict for Nada's exact payload
    infracost_result: Optional[InfraCostResult]
    deployops_result: Optional[DeployOpsResult]
    human_gates: HumanGates
    error_log: list[ErrorEntry]
    orchestrator_metadata: OrchestratorMetadata
    final_report: Optional[FinalReport]


# =============================================================================
# SECTION 2: SAFE NODE WRAPPER
# =============================================================================

def _safe_node_wrapper(node_func, node_name: str, state: OrchestratorState) -> OrchestratorState:
    """
    Safe wrapper for graph nodes.
    Catches exceptions, logs them, marks status as failed, and returns state.
    NO time.sleep() - async-friendly.
    """
    if state.get("status") == "failed":
        logger.warning(f"[{state['job_id']}] Skipping {node_name} - workflow already failed")
        return state
    
    try:
        result = node_func(state)
        return result
    except Exception as e:
        logger.error(f"[{state['job_id']}] {node_name} failed: {e}")
        
        error_entry: ErrorEntry = {
            "node": node_name,
            "attempt": 1,
            "max_attempts": 3,
            "message": str(e),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "stack_trace": str(e.__traceback__) if e.__traceback__ else None,
            "resolved": False,
        }
        
        state["error_log"].append(error_entry)
        state["status"] = "failed"
        state["updated_at"] = datetime.now(timezone.utc).isoformat()
        return state


# =============================================================================
# SECTION 3: MOCK AGENT FUNCTIONS (Sprint 1)
# =============================================================================

def _mock_codesec_agent_impl(state: OrchestratorState) -> OrchestratorState:
    """MOCK: CodeSec Agent (Nada). CDC: US-1.1.1 to US-1.1.6"""
    logger.info(f"[{state['job_id']}] Running MOCK CodeSec Agent for: {state['repo_url']}")

    state["status"] = "analyzing"
    state["orchestrator_metadata"]["current_node"] = "codesec_agent"
    state["orchestrator_metadata"]["nodes_executed"].append("codesec_agent")
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    state["codesec_result"] = {
        "job_id": state["job_id"],
        "status": "completed",
        "error": None,
        "repo_url": state["repo_url"],
        "repo_metadata": {
            "name": "repo-name",
            "branch": "main",
            "commit_sha": "a1b2c3d4e5f6",
            "total_files": 150,
            "loc": 8500,
            "language_breakdown": {
                "python": 6200,
                "javascript": 1500,
                "dockerfile": 200,
                "terraform": 600
            }
        },
        "phases": [
            {"name": "clone", "status": "completed", "started_at": "2026-07-08T10:00:00Z", "completed_at": "2026-07-08T10:00:05Z"},
            {"name": "stack_detection", "status": "completed", "started_at": "2026-07-08T10:00:06Z", "completed_at": "2026-07-08T10:00:10Z"},
            {"name": "sast", "status": "completed", "started_at": "2026-07-08T10:00:11Z", "completed_at": "2026-07-08T10:00:20Z"},
            {"name": "secrets", "status": "completed", "started_at": "2026-07-08T10:00:21Z", "completed_at": "2026-07-08T10:00:25Z"},
            {"name": "dependencies", "status": "completed", "started_at": "2026-07-08T10:00:26Z", "completed_at": "2026-07-08T10:00:30Z"},
            {"name": "dockerfile_scan", "status": "completed", "started_at": "2026-07-08T10:00:31Z", "completed_at": "2026-07-08T10:00:35Z"},
            {"name": "sbom", "status": "completed", "started_at": "2026-07-08T10:00:36Z", "completed_at": "2026-07-08T10:00:40Z"},
            {"name": "scoring", "status": "completed", "started_at": "2026-07-08T10:00:41Z", "completed_at": "2026-07-08T10:00:45Z"}
        ],
        "summary": {
            "files_scanned": 150,
            "sast_findings_count": 12,
            "secrets_found_count": 2,
            "vulnerable_dependencies_count": 1,
            "dockerfile_issues_count": 3,
            "total_critical": 1,
            "total_high": 4,
            "total_medium": 5,
            "total_low": 2,
            "total_info": 0
        },
        "stack_detection": {
            "primary_language": "python",
            "frameworks": ["fastapi", "sqlalchemy"],
            "database": "postgresql",
            "build_tool": "pip",
            "container": {
                "detected": True,
                "base_image": "python:3.12-slim",
                "dockerfile_path": "Dockerfile",
                "compose_detected": True
            },
            "confidence": 0.92,
            "detected_files": ["requirements.txt", "Dockerfile", "main.py", "docker-compose.yml"]
        },
        "sast_findings": [
            {
                "rule_id": "python.sql-injection",
                "tool": "semgrep",
                "severity": "critical",
                "category": "owasp-top10",
                "owasp_category": "A03:2021 - Injection",
                "cwe_id": "CWE-89",
                "file": "app/db.py",
                "line": 24,
                "column": 10,
                "message": "Possible SQL injection via string concatenation",
                "snippet": 'query = f"SELECT * FROM users WHERE id = {user_id}"',
                "remediation": "Use parameterized queries with SQLAlchemy ORM"
            },
            {
                "rule_id": "python.xss.generic",
                "tool": "semgrep",
                "severity": "medium",
                "category": "owasp-top10",
                "owasp_category": "A03:2021 - Injection",
                "cwe_id": "CWE-79",
                "file": "src/frontend/components/ChatPanel.tsx",
                "line": 15,
                "column": 5,
                "message": "Unsanitized user input rendered in DOM",
                "snippet": "<div dangerouslySetInnerHTML={{__html: userInput}} />",
                "remediation": "Use DOMPurify or React's built-in escaping"
            }
        ],
        "secrets": [
            {
                "type": "aws_access_key_id",
                "tool": "gitleaks",
                "file": ".env",
                "line": 3,
                "column": 1,
                "value_preview": "AKIAIOSFODNN7EXAMPLE",
                "commit_sha": "a1b2c3d4e5f6",
                "confidence": 0.95,
                "remediation": "Rotate the key and use AWS Secrets Manager"
            },
            {
                "type": "api_key",
                "tool": "gitleaks",
                "file": "scripts/deploy.sh",
                "line": 8,
                "column": 15,
                "value_preview": "sk-****abcd1234",
                "commit_sha": "a1b2c3d4e5f6",
                "confidence": 0.88,
                "remediation": "Use environment variables or a secret manager"
            }
        ],
        "dependencies": {
            "total_packages": 42,
            "direct": 12,
            "transitive": 30,
            "vulnerable_packages": [
                {
                    "package": "requests",
                    "installed_version": "2.25.0",
                    "fixed_version": "2.31.0",
                    "cve_id": "CVE-2023-32681",
                    "severity": "high",
                    "cvss_score": 7.5,
                    "description": "Unintended leak of Proxy-Authorization header"
                }
            ]
        },
        "dockerfile_findings": [
            {
                "rule_id": "DS001",
                "tool": "trivy",
                "severity": "high",
                "category": "dockerfile",
                "file": "Dockerfile",
                "line": 5,
                "message": "Running as root user",
                "snippet": "USER root",
                "remediation": "Add 'USER appuser' after creating non-root user"
            },
            {
                "rule_id": "DS002",
                "tool": "trivy",
                "severity": "medium",
                "category": "dockerfile",
                "file": "Dockerfile",
                "line": 1,
                "message": "Using 'latest' tag for base image",
                "snippet": "FROM python:latest",
                "remediation": "Pin to specific version: FROM python:3.12-slim"
            }
        ],
        "sbom": {
            "format": "CycloneDX",
            "specVersion": "1.5",
            "serialNumber": "urn:uuid:550e8400-e29b-41d4-a716-446655440001",
            "version": 1,
            "components_count": 42,
            "components": [
                {
                    "type": "library",
                    "name": "fastapi",
                    "version": "0.110.0",
                    "purl": "pkg:pypi/fastapi@0.110.0",
                    "licenses": [{"id": "MIT"}],
                    "source_file": "requirements.txt"
                }
            ],
            "download_url": f"/api/jobs/{state['job_id']}/sbom/download"
        },
        "security_score": {
            "score": 68,
            "grade": "C",
            "max_score": 100,
            "breakdown": {
                "sast": 20,
                "secrets": 15,
                "dependencies": 20,
                "dockerfile": 8,
                "sbom": 10,
                "stack_detection": 7
            },
            "severity_counts": {
                "critical": 1,
                "high": 4,
                "medium": 5,
                "low": 2,
                "info": 0
            },
            "recommendations": [
                "Fix 1 critical SQL injection in app/db.py:24",
                "Update requests to >= 2.31.0 (CVE-2023-32681)",
                "Remove 2 hardcoded secrets from .env and scripts/deploy.sh",
                "Run Dockerfile as non-root user (Dockerfile:5)"
            ]
        }
    }

    score = state["codesec_result"]["security_score"]["score"]
    grade = state["codesec_result"]["security_score"]["grade"]
    logger.info(f"[{state['job_id']}] CodeSec complete. Score: {score}/100 (Grade {grade})")
    return state


def _mock_infracost_agent_impl(state: OrchestratorState) -> OrchestratorState:
    """MOCK: InfraCost Agent (Karim). Sprint 1 mock data."""
    logger.info(f"[{state['job_id']}] Running MOCK InfraCost Agent")

    state["status"] = "infra_generating"
    state["orchestrator_metadata"]["current_node"] = "infracost_agent"
    state["orchestrator_metadata"]["nodes_executed"].append("infracost_agent")
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    state["infracost_result"] = {
        "architecture_recommendation": "ecs_fargate",
        "justification": "FastAPI app with moderate traffic -> ECS Fargate for serverless containers without EC2 management",
        "generated_terraform": {
            "main_tf": 'resource "aws_ecs_cluster" "app" {\n  name = "devguard-app"\n}',
            "variables_tf": 'variable "aws_region" {\n  default = "us-east-1"\n}',
            "outputs_tf": 'output "alb_dns" {\n  value = aws_lb.app.dns_name\n}',
            "plan_passed": True,
        },
        "cost_estimate": {
            "monthly_cost_usd": 145.32,
            "currency": "USD",
            "breakdown": [
                {"service": "ECS Fargate", "monthly_cost_usd": 89.50},
                {"service": "ALB", "monthly_cost_usd": 22.80},
                {"service": "RDS PostgreSQL", "monthly_cost_usd": 33.02},
            ],
        },
        "load_scenarios": [
            {"users": 1000, "estimated_monthly_cost_usd": 145.32, "scaling_assumptions": "1 vCPU, 2GB RAM, single AZ"},
            {"users": 10000, "estimated_monthly_cost_usd": 420.15, "scaling_assumptions": "2 vCPU, 4GB RAM, multi-AZ"},
            {"users": 100000, "estimated_monthly_cost_usd": 1850.00, "scaling_assumptions": "Auto-scaling 2-10 tasks, multi-AZ, read replicas"},
        ],
        "optimizations": [
            {"strategy": "graviton", "projected_savings_usd": 25.40, "description": "Switch to Graviton2/3 processors for 20% price reduction"},
            {"strategy": "reserved_instances", "projected_savings_usd": 35.00, "description": "1-year reserved capacity for baseline load"},
        ],
        "region_comparison": [
            {"region": "us-east-1", "monthly_cost_usd": 145.32},
            {"region": "eu-west-1", "monthly_cost_usd": 162.80},
            {"region": "ap-southeast-1", "monthly_cost_usd": 158.45},
        ],
    }

    logger.info(f"[{state['job_id']}] InfraCost complete. Est. cost: ${state['infracost_result']['cost_estimate']['monthly_cost_usd']}/mo")
    return state


def _mock_deployops_agent_impl(state: OrchestratorState) -> OrchestratorState:
    """
    MOCK: DeployOps Agent (Oussema). Sprint 1 mock data.
    ALIGNED with deployops-mock-schema.json v1.0
    """
    logger.info(f"[{state['job_id']}] Running MOCK DeployOps Agent")

    state["status"] = "deploying"
    state["orchestrator_metadata"]["current_node"] = "deployops_agent"
    state["orchestrator_metadata"]["nodes_executed"].append("deployops_agent")
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    # ALIGNED with deployops-mock-schema.json - all required fields present
    state["deployops_result"] = {
        # ===== CHAMPS REQUIS par deployops-mock-schema.json =====
        "job_id": state["job_id"],  # ← REQUIS: doit matcher l'orchestrateur
        "deployment_status": "success",
        "deployed_url": "https://devguard-app-123456.us-east-1.elb.amazonaws.com",
        "health_check": {
            "passed": True,
            "response_time_ms": 245,
            "status_code": 200,
            "checked_at": datetime.now(timezone.utc).isoformat(),
        },
        "rollback_triggered": False,
        "rollback_reason": None,
        "error": None,
        "terraform_outputs": {
            "ecs_cluster_name": "devguard-app",
            "service_name": "devguard-api",
            "alb_dns": "devguard-app-123456.us-east-1.elb.amazonaws.com",
        },
        
        # ===== CHAMPS OPTIONNELS du schema =====
        "artifacts": {
            "terraform": {
                "files": {
                    "main.tf": 'resource "aws_instance" "web" {\n  ami = "ami-12345678"\n  instance_type = "t3.micro"\n}',
                    "variables.tf": 'variable "region" {\n  default = "us-east-1"\n}',
                    "outputs.tf": 'output "url" {\n  value = aws_instance.web.public_dns\n}'
                },
                "variables": {
                    "region": "us-east-1",
                    "environment": "dev"
                }
            },
            "dockerfile": "FROM python:3.12\nCOPY . /app\nCMD [\"python\", \"app.py\"]",
            "docker_image": {
                "name": "devguard-app",
                "tag": "latest"
            },
            "source_code": "/tmp/repo_abc123"
        },
        "aws_config": {
            "region": "us-east-1",
            "ecs_cluster": "devguard-cluster",
            "service_name": "app-service",
            "task_cpu": "256",
            "task_memory": "512"
        },
        "deployment_config": {
            "strategy": "rolling",
            "health_check_path": "/health",
            "health_check_port": 8080,
            "timeout_minutes": 5,
            "min_healthy_percent": 50,
            "max_percent": 200
        },
        "approval": {
            "deploy_approved": True,
            "approved_by": "user@email.com"
        }
    }

    logger.info(f"[{state['job_id']}] DeployOps complete. URL: {state['deployops_result']['deployed_url']}")
    return state


# =============================================================================
# SECTION 4: HUMAN GATES
# =============================================================================

def _human_gate_1_impl(state: OrchestratorState) -> OrchestratorState:
    """Human Approval Gate 1: After CodeSec, before InfraCost. CDC: US-2.2.3"""
    logger.info(f"[{state['job_id']}] HUMAN GATE 1: Pre-InfraCost approval required")

    state["status"] = "awaiting_approval_gate_1"
    state["orchestrator_metadata"]["current_node"] = "human_gate_1"
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    codesec = state.get("codesec_result") or {}
    security_score = codesec.get("security_score", {}).get("score", 0)
    grade = codesec.get("security_score", {}).get("grade", "N/A")
    sast_findings = codesec.get("sast_findings", [])
    secrets = codesec.get("secrets", [])
    recommendations = codesec.get("security_score", {}).get("recommendations", [])

    approval = interrupt({
        "gate": "gate_1_pre_infracost",
        "message": "CodeSec analysis complete. Approve to proceed with infrastructure generation?",
        "context": {
            "security_score": security_score,
            "grade": grade,
            "vulnerabilities_count": len(sast_findings),
            "secrets_count": len(secrets),
            "recommendations": recommendations,
        },
        "actions": ["approve", "reject"],
    })

    gate = state["human_gates"]["gate_1_pre_infracost"]
    gate["approved"] = approval.get("approved", False)
    gate["comment"] = approval.get("comment", "")
    gate["approved_at"] = datetime.now(timezone.utc).isoformat()
    gate["approved_by"] = approval.get("approved_by", "unknown")

    if not gate["approved"]:
        logger.warning(f"[{state['job_id']}] Gate 1 REJECTED. Workflow halted.")
        state["status"] = "failed"
        state["error_log"].append({
            "node": "human_gate_1",
            "attempt": 1,
            "max_attempts": 1,
            "message": f"Human gate 1 rejected: {approval.get('comment', 'No comment')}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "stack_trace": None,
            "resolved": False,
        })
    else:
        logger.info(f"[{state['job_id']}] Gate 1 APPROVED. Proceeding to InfraCost.")

    return state


def _human_gate_2_impl(state: OrchestratorState) -> OrchestratorState:
    """Human Approval Gate 2: After InfraCost, before DeployOps. CDC: US-2.2.3"""
    logger.info(f"[{state['job_id']}] HUMAN GATE 2: Pre-DeployOps approval required")

    state["status"] = "awaiting_approval_gate_2"
    state["orchestrator_metadata"]["current_node"] = "human_gate_2"
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    infracost = state.get("infracost_result") or {}
    cost_estimate = infracost.get("cost_estimate", {})
    monthly_cost = cost_estimate.get("monthly_cost_usd", 0)
    architecture = infracost.get("architecture_recommendation", "unknown")
    breakdown = cost_estimate.get("breakdown", [])

    approval = interrupt({
        "gate": "gate_2_pre_deployops",
        "message": "InfraCost complete. Review cost estimate and approve deployment?",
        "context": {
            "monthly_cost_usd": monthly_cost,
            "architecture": architecture,
            "breakdown": breakdown,
        },
        "actions": ["approve", "reject"],
    })

    gate = state["human_gates"]["gate_2_pre_deployops"]
    gate["approved"] = approval.get("approved", False)
    gate["comment"] = approval.get("comment", "")
    gate["approved_at"] = datetime.now(timezone.utc).isoformat()
    gate["approved_by"] = approval.get("approved_by", "unknown")

    if not gate["approved"]:
        logger.warning(f"[{state['job_id']}] Gate 2 REJECTED. Workflow halted.")
        state["status"] = "failed"
        state["error_log"].append({
            "node": "human_gate_2",
            "attempt": 1,
            "max_attempts": 1,
            "message": f"Human gate 2 rejected: {approval.get('comment', 'No comment')}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "stack_trace": None,
            "resolved": False,
        })
    else:
        logger.info(f"[{state['job_id']}] Gate 2 APPROVED. Proceeding to DeployOps.")

    return state


# =============================================================================
# SECTION 5: HEALTH CHECK & REPORT
# =============================================================================

def _health_check_impl(state: OrchestratorState) -> OrchestratorState:
    """Health check verification after deployment. CDC: US-1.2.2"""
    logger.info(f"[{state['job_id']}] Running health check...")

    state["status"] = "health_checking"
    state["orchestrator_metadata"]["current_node"] = "health_check"
    state["orchestrator_metadata"]["nodes_executed"].append("health_check")
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    deployops = state.get("deployops_result")
    if deployops and deployops.get("health_check", {}).get("passed"):
        logger.info(f"[{state['job_id']}] Health check PASSED")
        state["status"] = "completed"
    else:
        logger.error(f"[{state['job_id']}] Health check FAILED. Triggering rollback...")
        state["status"] = "rolled_back"
        if deployops:
            deployops["rollback_triggered"] = True
            deployops["rollback_reason"] = "Health check failed after deployment"
            deployops["deployment_status"] = "rolled_back"

    return state


def _generate_report_impl(state: OrchestratorState) -> OrchestratorState:
    """Generate final report with all agent results. CDC: US-2.2.6"""
    logger.info(f"[{state['job_id']}] Generating final report...")

    state["orchestrator_metadata"]["current_node"] = "generate_report"
    state["orchestrator_metadata"]["nodes_executed"].append("generate_report")
    state["updated_at"] = datetime.now(timezone.utc).isoformat()

    codesec = state.get("codesec_result") or {}
    summary = codesec.get("summary", {})
    vuln_count = summary.get("sast_findings_count", 0)
    critical_count = summary.get("total_critical", 0)

    infracost = state.get("infracost_result") or {}
    cost_estimate = infracost.get("cost_estimate", {})
    monthly_cost = cost_estimate.get("monthly_cost_usd", 0.0)

    deployops = state.get("deployops_result")
    deploy_status = deployops.get("deployment_status", "not_deployed") if deployops else "not_deployed"

    recommendations = []
    security_score = codesec.get("security_score", {})
    if security_score and security_score.get("recommendations"):
        recommendations.extend(security_score["recommendations"])
    
    optimizations = infracost.get("optimizations", [])
    if optimizations:
        recommendations.extend([opt.get("description", "") for opt in optimizations])

    start_time = datetime.fromisoformat(state["orchestrator_metadata"]["start_time"].replace("Z", "+00:00"))
    elapsed = (datetime.now(timezone.utc) - start_time).total_seconds()
    state["orchestrator_metadata"]["elapsed_seconds"] = elapsed

    state["final_report"] = {
        "format": "html",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "download_url": None,
        "summary": {
            "total_vulnerabilities": vuln_count,
            "critical_count": critical_count,
            "estimated_monthly_cost_usd": monthly_cost,
            "deployment_status": deploy_status,
            "recommendations": recommendations,
            "pipeline_duration_seconds": elapsed,
        },
    }

    logger.info(f"[{state['job_id']}] Report generated in {elapsed:.2f}s.")
    return state


# =============================================================================
# SECTION 6: CONDITIONAL ROUTING
# =============================================================================

def route_after_codesec(state: OrchestratorState) -> str:
    if state.get("status") == "failed":
        return "end"
    if state.get("codesec_result") is None:
        return "end"
    return "human_gate_1"


def route_after_gate_1(state: OrchestratorState) -> str:
    if state.get("status") == "failed":
        return "end"
    if state["human_gates"]["gate_1_pre_infracost"]["approved"]:
        return "infracost_agent"
    return "end"


def route_after_infracost(state: OrchestratorState) -> str:
    if state.get("status") == "failed":
        return "end"
    if state.get("infracost_result") is None:
        return "end"
    return "human_gate_2"


def route_after_gate_2(state: OrchestratorState) -> str:
    if state.get("status") == "failed":
        return "end"
    if state["human_gates"]["gate_2_pre_deployops"]["approved"]:
        return "deployops_agent"
    return "end"


def route_after_deployops(state: OrchestratorState) -> str:
    if state.get("status") == "failed":
        return "end"
    if state.get("deployops_result") is None:
        return "end"
    return "health_check"


def route_after_health_check(state: OrchestratorState) -> str:
    if state.get("status") == "completed":
        return "generate_report"
    return "end"


# =============================================================================
# SECTION 7: GRAPH CONSTRUCTION
# =============================================================================

def build_orchestrator_graph() -> StateGraph:
    """
    Build and compile the LangGraph state graph.
    
    NOTE: Uses MemorySaver for Sprint 1. 
    TODO Sprint 2: Replace with PostgresSaver for persistence across restarts.
    """
    builder = StateGraph(OrchestratorState)

    builder.add_node(
        "codesec_agent",
        lambda s: _safe_node_wrapper(_mock_codesec_agent_impl, "codesec_agent", s)
    )
    builder.add_node(
        "human_gate_1",
        lambda s: _safe_node_wrapper(_human_gate_1_impl, "human_gate_1", s)
    )
    builder.add_node(
        "infracost_agent",
        lambda s: _safe_node_wrapper(_mock_infracost_agent_impl, "infracost_agent", s)
    )
    builder.add_node(
        "human_gate_2",
        lambda s: _safe_node_wrapper(_human_gate_2_impl, "human_gate_2", s)
    )
    builder.add_node(
        "deployops_agent",
        lambda s: _safe_node_wrapper(_mock_deployops_agent_impl, "deployops_agent", s)
    )
    builder.add_node(
        "health_check",
        lambda s: _safe_node_wrapper(_health_check_impl, "health_check", s)
    )
    builder.add_node(
        "generate_report",
        lambda s: _safe_node_wrapper(_generate_report_impl, "generate_report", s)
    )

    builder.set_entry_point("codesec_agent")

    builder.add_conditional_edges(
        "codesec_agent",
        route_after_codesec,
        {"human_gate_1": "human_gate_1", "end": END}
    )
    builder.add_conditional_edges(
        "human_gate_1",
        route_after_gate_1,
        {"infracost_agent": "infracost_agent", "end": END}
    )
    builder.add_conditional_edges(
        "infracost_agent",
        route_after_infracost,
        {"human_gate_2": "human_gate_2", "end": END}
    )
    builder.add_conditional_edges(
        "human_gate_2",
        route_after_gate_2,
        {"deployops_agent": "deployops_agent", "end": END}
    )
    builder.add_conditional_edges(
        "deployops_agent",
        route_after_deployops,
        {"health_check": "health_check", "end": END}
    )
    builder.add_conditional_edges(
        "health_check",
        route_after_health_check,
        {"generate_report": "generate_report", "end": END}
    )
    builder.add_edge("generate_report", END)

    memory = MemorySaver()
    graph = builder.compile(checkpointer=memory)

    logger.info("Orchestrator graph compiled successfully (v1.0.2).")
    return graph


# =============================================================================
# SECTION 8: PUBLIC API
# =============================================================================

def create_initial_state(repo_url: str) -> OrchestratorState:
    """Create the initial state for a new workflow."""
    now = datetime.now(timezone.utc).isoformat()
    job_id = str(uuid.uuid4())

    return {
        "job_id": job_id,
        "repo_url": repo_url,
        "status": "pending",
        "created_at": now,
        "updated_at": now,
        "codesec_result": None,
        "infracost_result": None,
        "deployops_result": None,
        "human_gates": {
            "gate_1_pre_infracost": {
                "required": True,
                "approved": None,
                "comment": None,
                "approved_at": None,
                "approved_by": None,
            },
            "gate_2_pre_deployops": {
                "required": True,
                "approved": None,
                "comment": None,
                "approved_at": None,
                "approved_by": None,
            },
        },
        "error_log": [],
        "orchestrator_metadata": {
            "graph_version": "1.0.2",
            "start_time": now,
            "elapsed_seconds": 0.0,
            "current_node": "start",
            "nodes_executed": [],
            "chat_session_id": None,
        },
        "final_report": None,
    }


def run_workflow(repo_url: str, thread_id: Optional[str] = None) -> OrchestratorState:
    """
    Run the complete orchestrator workflow for a repository.
    
    NOTE: For human gates, execution will pause at interrupt points.
    Resume with: graph.invoke(None, config, resume_after_interrupt=True)
    """
    graph = build_orchestrator_graph()
    state = create_initial_state(repo_url)
    config = {"configurable": {"thread_id": thread_id or state["job_id"]}}

    logger.info(f"Starting workflow for job {state['job_id']} | repo: {repo_url}")

    try:
        final_state = graph.invoke(state, config)
        logger.info(f"Workflow completed for job {state['job_id']} | status: {final_state['status']}")
        return final_state
    except Exception as e:
        logger.error(f"Workflow failed for job {state['job_id']}: {e}")
        state["status"] = "failed"
        state["error_log"].append({
            "node": "orchestrator",
            "attempt": 1,
            "max_attempts": 1,
            "message": str(e),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "stack_trace": str(e.__traceback__) if e.__traceback__ else None,
            "resolved": False,
        })
        return state


# =============================================================================
# SECTION 9: MAIN
# =============================================================================

if __name__ == "__main__":
    test_repo = "https://github.com/NadaBhm/devguard-ai"

    print("=" * 60)
    print("DevGuard AI - Orchestrator Test Run")
    print("Version: 1.0.2 (Aligned with deployops-mock-schema.json)")
    print("=" * 60)

    state = create_initial_state(test_repo)
    print(f"\n[TEST 1] Initial state created:")
    print(f"  Job ID: {state['job_id']}")
    print(f"  Repo: {state['repo_url']}")
    print(f"  Status: {state['status']}")
    print(f"  Graph Version: {state['orchestrator_metadata']['graph_version']}")

    print(f"\n[TEST 2] Building graph...")
    graph = build_orchestrator_graph()
    print("  Graph compiled successfully!")

    print(f"\n[TEST 3] Running workflow (will pause at human gates)...")
    config = {"configurable": {"thread_id": state["job_id"]}}
    
    try:
        for event in graph.stream(state, config):
            for node_name, node_state in event.items():
                if node_name == "__interrupt__":
                    print(f"\n  ⏸️  INTERRUPT at gate: {node_state[0]['value']['gate']}")
                    print(f"     Message: {node_state[0]['value']['message']}")
                    print(f"     Actions: {node_state[0]['value']['actions']}")
                    print(f"\n  To resume, call: graph.invoke(None, config, resume_after_interrupt=True)")
                    break
                else:
                    status = node_state.get("status", "unknown")
                    print(f"  ✅ Node '{node_name}' completed | status: {status}")
    except Exception as e:
        print(f"  ❌ Error: {e}")

    print("\n" + "=" * 60)
    print("Test complete.")
    print("=" * 60) 